spring:
  application:
    name: reminders
    config:
      activate:
        on-profile: prod
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: ${OAUTH2_CLIENT_ID:client_id}
            client-secret: ${OAUTH2_CLIENT_SECRET:client_secret}
            scope:
              - profile
              - email
  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url:  jdbc:postgresql://${POSTGRES_URL:localhost}:${POSTGRES_PORT:5432}/postgres
    username: postgres_user
    password: postgres_password
    driver-class-name: org.postgresql.Driver
    # HikariCP settings
    hikari:
      minimumIdle: 5
      maximumPoolSize: 15
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: remindersPool

telegram:
  bot:
    username: ${TELEGRAM_BOT_NAME:telegram_secret}
    token: ${TELEGRAM_BOT_TOKEN:telegram_token}

quartz:
  sendMessageInterval:
    seconds: 30

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    oauth:
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
      scopes: email, profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

mail:
  email: ${EMAIL_SEND_FROM:macsimmax1996@mail.ru}
  password: ${EMAIL_PASSWORD_SEND_FROM:hINIEAiP6QbUSVaQrTNL}

logging:
  level:
    org:
      springframework:
        security: INFO
