spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url:  jdbc:tc:postgresql://localhost/myappdb
    username: user
    password: password
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

telegram:
  bot:
    username: bot_name
    token: token

mail:
  email: mail@mail.ru
  password: test
